### ISSUE TITLE
data-source phone and trunk base settings not found

### ISSUE THREAD

**Issue by PsserviceHH** [MyPureCloud/terraform-provider-genesyscloud#186] opened 2022-01-16 16:59 UTC
Hey everyone,

i'm using the 1.0.1 genesyscloud terraform module within Terraform Cloud. I'm not able to get any base settings - doesn't matter if phone or trunk base settings. 

error message:
Error: No trunkBaseSettings found with name SBC
with data.genesyscloud_telephony_providers_edges_trunkbasesettings.trunkBaseSettingSBC
on datasource.tf line 83, in data "genesyscloud_telephony_providers_edges_trunkbasesettings" "trunkBaseSettingSBC":
data "genesyscloud_telephony_providers_edges_trunkbasesettings" "trunkBaseSettingSBC" {

the configuration (datasource.tf):

data "genesyscloud_telephony_providers_edges_trunkbasesettings" "trunkBaseSettingSBC" {
  name = "SBC"
}

If i'm using the API Explorer i can see all basesettings based on the name. (/api/v2/telephony/providers/edges/trunkbasesettings)

thanks,
Pierre

**Comment by ronanwatkins** [comment] 2022-01-21 15:00
Hi Pierre, I'm not able to reproduce your error. Also, an issue like that would cause our acceptance tests to fail.

Are you sure that you are targeting the correct Genesys Cloud Org?

**Comment by motomeru** [comment] 2022-03-08 15:40
Hi @ronanwatkins I had very similar problem I created a ticket on GC CustomerCare:

--------------------------------------------------------------------------------
Hi Genesys Team,

for now we are using Terraform for CI/CD for our 3 organizations. we found that we cannot use data source for phone trunks:

as an example I tried to use:

data "genesyscloud_telephony_providers_edges_trunkbasesettings" "testTrunkBaseSettings" {
name = "Default SIP Phone Connection"
}

i received an error that name cannot be found.

Can you try to reproduce that?

-------------------------------------------------------------------------------

They wrote that they cannot help with that and i should ask terraform community about that :)

**Comment by ronanwatkins** [comment] 2022-03-08 15:58
Hi @motomeru, I can't reproduce this. Can you try the latest version of our provider?

**Comment by motomeru** [comment] 2022-03-14 08:56
Hey @ronanwatkins I used fresh 1.1.3 version with the same error:

│ Error: No trunkBaseSettings found with name Default SIP Phone Connection

my code:

`data "genesyscloud_telephony_providers_edges_trunkbasesettings" "testTrunkBaseSettings" {
name = "Default SIP Phone Connection"
}`

Default SIP Phone Connection is the default one phone trunk in GC:

![image](https://user-images.githubusercontent.com/10912411/158138071-183ebabf-45a9-4554-911e-9430d61aecb0.png)

**Comment by ronanwatkins** [comment] 2022-03-15 14:56
Hi @motomeru, @PsserviceHH,

I have been able to replicate and fix this issue. Trunk base settings with certain attributes were being omitted in the search.
The fix will be included in the next release of this provider.

**Closed** 2022-04-19 08:11 UTC
