### ISSUE TITLE
Malformed Syntax with Integration Actions

### ISSUE THREAD

**Issue by scase011** [MyPureCloud/terraform-provider-genesyscloud#500] opened 2023-04-19 15:26 UTC
While trying to deploy a new integration action I am getting an error message : API Error: 400 - The request could not be understood by the server due to malformed syntax. I have deployed numerous other Genesys resources without issue. I have copied the code from the documentation (https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/integration_action), the same way I did for the other resources. I have also run terraform validate and it says the format is correct. 

I believe the error may have something to do with jsonencode aspect of this resource, but the error message does not provide much information for me to debug with.

Any assistance is appreciated. Thanks.

**Comment by carnellj-genesys** [comment] 2023-04-19 17:25
Hi Scase011,

What I normally do is create the data action manually in Genesys Cloud and then use the CLI to extract the JSON and copy it the CX as Code component.  I would suggest you do this and compare that with what you have in the CX as Code component.  That is the first thing I would do.  A 400 indicates the JSON is malformed.  We take what is coming in JSON and just pass it through in the component.

I would encourage you to also take a look at our https://github.com/genesysCloudDevOps repository.  We have a ton of CX as Code data actions you can look at and compare.   Also, in the future, I would recommend you post to our forum (https://developer.genesys.cloud/forums) with a question like this.  We have a ton of developers across the company who monitor the forum.

Thanks,
    John Carnell

**Comment by scase011** [comment] 2023-04-19 18:04
Hello John,

I appreciate the response. I have tried this deployment with the input and output JSONs copied from an action within Genesys. I have also tried by copying the contracts from one of the modules in the code repository you linked. No matter what I input here, I always get this malformed syntax error. I have also tried hard coding the integration id, just in case that reference was causing an issue, but still no luck. Below is one example of the code I have tried.

resource "genesyscloud_integration_action" "example-action" {
  name            = "Example Action"
  category        = "Genesys Cloud Data Action"
  integration_id  = data.genesyscloud_integration.example_integration_name.id
  contract_input  = jsonencode({
    "type" = "object",
    "additionalProperties" = true,
    "properties" = {
      "body" = {
        "type" = "string"
      }
    }
  })
  contract_output = jsonencode({
    "type" = "object",
    "additionalProperties" = true,
    "properties" = {
      "conversationId" = {
        "type" = "string"
      }
    }
  })
}

Does anything jump out as incorrect?

**Comment by carnellj-genesys** [comment] 2023-04-19 18:48
Hi,

Your JSON in the JSONEncode is malformed.  JSON does not use = (HCL does).  You json encode should look something like this:

```
contract_input = jsonencode({
"type": "object",
"additionalProperties": true,
"properties": {
"body": {
"type": "string"
}
}
})
```

Anytime you see a JSONEncode it needs to be valid JSON.

Thanks,
     John

**Comment by carnellj-genesys** [comment] 2023-06-08 15:39
Unable to reproduce after multiple variations an attempts.  Closing

**Closed by carnellj-genesys** 2023-06-08 15:39 UTC
